# Generated by Django 3.2.11 on 2022-01-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_auto_20220124_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='menu',
        ),
        migrations.CreateModel(
            name='MenuRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='lunch.menu')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='lunch.menu')),
            ],
        ),
    ]
