# Generated by Django 3.2.11 on 2022-01-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_auto_20220125_0724'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menurecipe',
            table='menu_recipe',
        ),
    ]
