# Generated by Django 3.2.11 on 2022-01-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_auto_20220125_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='recipes',
            field=models.ManyToManyField(related_name='recipes', through='lunch.MenuRecipe', to='lunch.Recipe'),
        ),
        migrations.AlterField(
            model_name='menurecipe',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_to_recipe', to='lunch.menu'),
        ),
        migrations.AlterField(
            model_name='menurecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_to_menu', to='lunch.recipe'),
        ),
    ]
